### ISSUE TITLE
A little more documentation for admins

### ISSUE THREAD

**Issue by nellePoint** [evolvingpixie/shrimp-akkome-fe#2]
hello, ive been spending a while trying to get this to work and was wondering if itd be possible to put some simple examples of what to do to set this up for your own instance?

**Comment by evolvingpixie** [comment]
I'll try to get some docs/examples up later this week. The gist of it though is host on a subdomain and route `/api`, and `/nodeinfo` to the iceshrimp backend/upstream and `/` to this backend/upstream. Alternatively you can build this yourself but modify `src/boot/after_store.js` to point to your iceshrimp domain. Similar to how wetdry.world does https://github.com/evolvingpixie/shrimp-akkome-fe/commit/5069a7b965136d0c6625e5d72e478784c8809112#diff-f0b59b811754fcb0fff660816066e4b9c57dc8c8f83bc43e4162288f23a93b65L372

**Comment by evolvingpixie** [comment]
Created https://github.com/evolvingpixie/shrimp-akkome-fe/wiki/Configuration-deployment that should give some direction as to how to host this.

**Comment by nellePoint** [comment]
thanks!
